Add PQC ML-DSA support (#785)
This PR adds the ability to support WebAuthn responses leveraging PQC
algorithms. Support for this is dependent on the runtime's support for
ML-DSA-44, ML-DSA-65, and ML-DSA-87. As of August 2026, the following
Deno and Node runtimes should support this:

- **Node**: v24.7.0 and up
- **Deno**: v2.8.2 and up

When the runtime does not support ML-DSA, SimpleWebAuthn will try to
help RPs understand this:

```
$ node -v
v22.23.2
$ node node_mldsa.mjs
Error: This runtime's WebCrypto.subtle does not support use of ML-DSA-44. See the `cause` property of this error for more info
    at verifyAKP (...)
    at async verifyAuthenticationResponse (...)
    at async file:///.../node_mldsa.mjs:5:20 {
  [cause]: DOMException [NotSupportedError]: Unrecognized algorithm name
      at normalizeAlgorithm (node:internal/crypto/util:366:11)
      at normalizeAlgorithm (node:internal/crypto/util:338:12)
      at SubtleCrypto.importKey (node:internal/crypto/webcrypto:572:15)
      at importJWKKey (...)
      at async verifyAKP (...)
      at async verifyAuthenticationResponse (...)
      at async file:///.../node_mldsa.mjs:5:20
}
```

Fixes #770.